In [2]:
import requests

In [7]:
 url = 'http://openapi.seoul.go.kr:8088/4875635778616c733132374b73524659/json/SebcCollegeInfoKor/1/100/'

In [8]:
response = requests.get(url)

In [9]:
data = response.json()
data

{'SebcCollegeInfoKor': {'list_total_count': 64,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'MAIN_KEY': 'BE_LiST23-0034',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울시립대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '공립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 서울시립대로 163 (전농동 90번지) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '휘경2동',
    'TEL': '02-6490-6114',
    'FAX': '02-2210-5576',
    'HP': 'http://www.uos.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0035',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '서울여자간호대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 홍제3동 서울여자간호대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제2동',
    'TEL': '02-2287-1700',
    'FAX': '02-395-8018',
    'HP': 'http://www.snjc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0036',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 화랑로 621 서울여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '공릉2동',
    'TEL': '02-970-5114',
    'FAX': '02-978-7931',
    'HP': 'http://www.swu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0037',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '서일대학교',
    'BRANCH': '본교',
    'STATE': '학교명 변경',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중랑구',
    'H_KOR_DONG': '면목제3.8동',
    'TEL': '02-490-7300',
    'FAX': '02-493-2576',
    'HP': 'http://www.seoil.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0038',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성공회대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 항동 성공회대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '오류2동',
    'TEL': '02-2610-4142',
    'FAX': '02-2610-4248',
    'HP': 'http://www.skhu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0039',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성균관대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 명륜동3가 성균관대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '종로1.2.3.4가동',
    'TEL': '02-760-0114',
    'FAX': '',
    'HP': 'http://www.skku.edu'},
   {'MAIN_KEY': 'BE_LiST23-0040',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성신여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 동선동3가 성신여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '동선동',
    'TEL': '02-920-7114',
    'FAX': '02-920-2018',
    'HP': 'http://www.sungshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0041',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '세종대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 군자동 세종대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '군자동',
    'TEL': '02-3408-3114',
    'FAX': '02-3408-3906',
    'HP': 'http://www.sejong.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0042',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숙명여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 청파로47길 100 숙명여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '청파동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.sookmyung.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0043',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숭실대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 상도동 511 숭실대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '상도1동',
    'TEL': '02-820-0114',
    'FAX': '',
    'HP': 'http://www.ssu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0044',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '숭의여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 중구 소파로2길 10(예장동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-3708-9000',
    'FAX': '02-773-2625',
    'HP': 'http://www.sewc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0045',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '연세대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 신촌동 연세대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-2123-2114',
    'FAX': '02-392-0618',
    'HP': 'http://www.yonsei.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0046',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '이화여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 대현동 11-1 이화여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-3277-2114',
    'FAX': '02-393-5903',
    'HP': 'http://www.ewha.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0047',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '인덕대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 초안산로 12',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계2동',
    'TEL': '02-950-7000',
    'FAX': '02-906-5340',
    'HP': 'http://www.induk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0048',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '장로회신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 광장로 5길 25-1(광장동) 장로회신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '광장동',
    'TEL': '02-450-0700',
    'FAX': '',
    'HP': 'http://www.pcts.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0049',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '적십자간호대학',
    'BRANCH': '본교',
    'STATE': '폐교',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 경교장길8',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '교남동',
    'TEL': '02-3700-3600',
    'FAX': '02-3700-3400',
    'HP': 'http://redcross.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0050',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '중앙대학교 서울캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 흑석로 84',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '흑석동',
    'TEL': '02-820-5114',
    'FAX': '',
    'HP': 'http://www.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0051',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '총신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 사당동 산31-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '사당3동',
    'TEL': '02-3479-0200',
    'FAX': '02-536-2602',
    'HP': 'http://www.chongshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0052',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '추계예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 북아현동 190-1 추계예술대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-362-5700',
    'FAX': '02-392-1777',
    'HP': 'http://www.chugye.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0053',
    'YEAR': '2013',
    'CATE1_NAME': '방송통신대학',
    'NAME_KOR': '한국방송통신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 동숭동 한국방송통신대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-3668-4114',
    'FAX': '02-744-5882',
    'HP': 'http://www.knou.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0054',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국성서대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 상계7동 한국성서대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '상계6.7동',
    'TEL': '02-950-5401',
    'FAX': '02-950-5411',
    'HP': 'http://www.bible.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0055',
    'YEAR': '2013',
    'CATE1_NAME': '각종대학(대학)',
    'NAME_KOR': '한국예술종합학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '특별법국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 석관동 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '석관동',
    'TEL': '',
    'FAX': '',
    'HP': ''},
   {'MAIN_KEY': 'BE_LiST23-0056',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국외국어대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 이문로 107',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '이문1동',
    'TEL': '02-2173-2114',
    'FAX': '',
    'HP': 'http://www.hufs.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0057',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국체육대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 송파구 오륜동 한국체육대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '송파구',
    'H_KOR_DONG': '오륜동',
    'TEL': '02-410-6564',
    'FAX': '02-410-6569',
    'HP': 'http://www.knsu.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0058',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍 I 대학 서울강서캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡동 산60-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '우장산동',
    'TEL': '02-2186-5800',
    'FAX': '02-2186-5819',
    'HP': 'http://kangseo.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0059',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍Ⅰ대학 서울정수캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 보광로 73(보광동 238)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '보광동',
    'TEL': '02-2001-4000',
    'FAX': '02-2001-4119',
    'HP': 'http://jungsu.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0060',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한성대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 삼선동3가 389 한성대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-760-4231',
    'FAX': '02-745-8943',
    'HP': 'http://www.hansung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0061',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한양대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 성동구 왕십리로 222 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2220-0114',
    'FAX': '',
    'HP': 'http://www.hanyang.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0062',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '한양여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성동구 행당동 살곶이길 200',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2290-2114',
    'FAX': '02-2291-6111',
    'HP': 'http://www.hywoman.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0063',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한영신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 경인로 290-42  한영신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '개봉1동',
    'TEL': '02-2067-4500',
    'FAX': '02-2616-4102',
    'HP': 'http://www.hytu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0064',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '홍익대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 마포구 와우산로 94(상수동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '마포구',
    'H_KOR_DONG': '서강동',
    'TEL': '02-320-1114',
    'FAX': '02-320-1122',
    'HP': 'http://www.hongik.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0001',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서초구 반포동 505',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서초구',
    'H_KOR_DONG': '반포4동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://songeui.catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0002',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제3캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 창경궁로 296-12(혜화동) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-740-9714',
    'FAX': '02-741-2801',
    'HP': 'http://catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0003',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '감리교신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 냉천동 감리교신학대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '천연동',
    'TEL': '02-361-9114',
    'FAX': '02-361-9299',
    'HP': 'http://www.mtu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0004',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '건국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 화양동',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '화양동',
    'TEL': '02-450-3114',
    'FAX': '02-450-4126',
    'HP': 'http://www.konkuk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0005',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경기대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 경기대로9길 24 경기대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-390-5114',
    'FAX': '031-249-8718',
    'HP': 'http://www.kyonggi.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0006',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경희대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 회기동 경희대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '회기동',
    'TEL': '02-961-0114',
    'FAX': '02-961-0930',
    'HP': 'http://www.khu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0007',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '고려대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 안암동 고려대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '안암동',
    'TEL': '02-3290-1114',
    'FAX': '',
    'HP': 'http://www.korea.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0008',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '광운대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 월계동 447-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계1동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.kw.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0009',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '국민대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 정릉3동 국민대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '정릉3동',
    'TEL': '02-910-4114',
    'FAX': '',
    'HP': 'http://www.kookmin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0010',
    'YEAR': '2013',
    'CATE1_NAME': '전공대학',
    'NAME_KOR': '국제예술대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강남구 논현동 79',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강남구',
    'H_KOR_DONG': '논현2동',
    'TEL': '02-542-8197',
    'FAX': '02-517-1392',
    'HP': 'http://www.kica.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0011',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '그리스도대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡6동 그리스도대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '화곡본동',
    'TEL': '02-2600-2400',
    'FAX': '02-2698-8876',
    'HP': 'http://kcu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0012',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '덕성여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 도봉구 삼양로 144길 33',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '도봉구',
    'H_KOR_DONG': '쌍문1동',
    'TEL': '02-901-8000',
    'FAX': '',
    'HP': 'http://www.duksung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0013',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중구 필동3가 동국대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-2260-3114',
    'FAX': '02-2277-1274',
    'HP': 'http://www.dongguk.edu'},
   {'MAIN_KEY': 'BE_LiST23-0014',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동덕여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 하월곡2동 동덕여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-940-4000',
    'FAX': '02-940-4182',
    'HP': 'http://www.dongduk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0015',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '동양미래대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 구로구 경인로 445 동양미래대학교 (고척동 62-160)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '고척1동',
    'TEL': '02-2610-1700',
    'FAX': '02-2688-5494',
    'HP': 'http://www.dongyang.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0016',
    'YEAR': '2013',
    'CATE1_NAME': '사이버대학(대학)',
    'NAME_KOR': '디지털서울문화예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 서대문구 통일로 37길 60 (홍제동 318-18)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제1동',
    'TEL': '02-2287-0222',
    'FAX': '02-379-8828',
    'HP': 'http://www.scau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0017',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '명지대학교 인문캠퍼스',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 남가좌동 50-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '남가좌2동',
    'TEL': '02-300-1556',
    'FAX': '02-300-1556',
    'HP': 'http://www.mju.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0018',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '명지전문대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',

In [12]:
import pandas as pd
temp = []
for d in data['SebcCollegeInfoKor']['row']:
    temp.append(d)
unl = pd.DataFrame(temp)
unl.head(3)

,MAIN_KEY,YEAR,CATE1_NAME,NAME_KOR,BRANCH,STATE,TYPE,POSTCODE,ADD_KOR,ADD_KOR_ROAD,H_KOR_CITY,H_KOR_GU,H_KOR_DONG,TEL,FAX,HP
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,,서울 동대문구 서울시립대로 163 (전농동 90번지),,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,,서울 서대문구 홍제3동 서울여자간호대학,,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,,서울특별시 노원구 화랑로 621 서울여자대학교,,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr

In [30]:
l_url = 'http://openapi.seoul.go.kr:8088/4875635778616c733132374b73524659/json/SeoulPublicLibraryInfo/1/100/'

In [31]:
l_response = requests.get(l_url)

In [33]:
l_data = l_response.json()
l_data

{'SeoulPublicLibraryInfo': {'list_total_count': 215,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'LBRRY_SEQ_NO': '1935',
    'LBRRY_NAME': '강남구립못골도서관',
    'GU_CODE': '0008',
    'CODE_VALUE': '강남구',
    'ADRES': '서울특별시 강남구 자곡로 116',
    'TEL_NO': '02-459-5522',
    'HMPG_URL': 'http://library.gangnam.go.kr/mglib',
    'OP_TIME': '평일 : 09:00~22:00, 주말 : 09:00~22:00',
    'FDRM_CLOSE_DATE': '매주 화요일 및 법정공휴일',
    'LBRRY_SE_NAME': '공공도서관',
    'XCNTS': '37.47153836',
    'YDNTS': '127.096582'},
   {'LBRRY_SEQ_NO': '1066',
    'LBRRY_NAME': '강남역삼푸른솔도서관',
    'GU_CODE': '0008',
    'CODE_VALUE': '강남구',
    'ADRES': '서울특별시 강남구 테헤란로8길 36. 4층',
    'TEL_NO': '02-2051-1178',
    'HMPG_URL': 'https://library.gangnam.go.kr/ysplib/index.do',
    'OP_TIME': '평일 : 09:00~18:00, 주말 : 09:00~17:00',
    'FDRM_CLOSE_DATE': '매주 화요일 및 법정 공휴일',
    'LBRRY_SE_NAME': '공공도서관',
    'XCNTS': '37.4964968',
    'YDNTS': '127.0320274'},
   {'LBRRY_SEQ_NO': '2815',
    'LBRRY_NAME': '개포하늘꿈도서관',
    'GU_CODE': '0008',
    'CODE_VALUE': '강남구',
    'ADRES': '서울특별시 강남구 개포로 110길 54',
    'TEL_NO': '02-451-1511',
    'HMPG_URL': 'https://library.gangnam.go.kr/hnkklib/',
    'OP_TIME': '평일 : 09:00~22:00, 주말 : 09:00~17:00',
    'FDRM_CLOSE_DATE': '매주 화요일 및 법정공휴일',
    'LBRRY_SE_NAME': '공공도서관',
    'XCNTS': '37.4906692944468',
    'YDNTS': '127.080356908422'},
   {'LBRRY_SEQ_NO': '48',
    'LBRRY_NAME': '논현도서관',
    'GU_CODE': '0008',
    'CODE_VALUE': '강남구',
    'ADRES': '서울특별시 강남구 학동로43길 17(논현동) 논현2동주민센터 6층',
    'TEL_NO': '02-3443-7650',
    'HMPG_URL': 'https://library.gangnam.go.kr/nhlib',
    'OP_TIME': '평일 : 09:00~22:00, 주말 : 09:00~17:00',
    'FDRM_CLOSE_DATE': '매주 화요일 및 법정공휴일',
    'LBRRY_SE_NAME': '공공도서관',
    'XCNTS': '37.5172779092976',
    'YDNTS': '127.037187913597'},
   {'LBRRY_SEQ_NO': '2843',
    'LBRRY_NAME': '논현문화마루도서관',
    'GU_CODE': '0008',
    'CODE_VALUE': '강남구',
    'ADRES': '서울특별시 강남구 논현로131길 40, 4~5층',
    'TEL_NO': '02-512-8580',
    'HMPG_URL': 'https://library.gangnam.go.kr/nmmlib',
    'OP_TIME': '평일 : 09:00~18:00, 주말 : 09:00~17:00',
    'FDRM_CLOSE_DATE': '매주 월요일 및 법정공휴일',
    'LBRRY_SE_NAME': '공공도서관',
    'XCNTS': '37.51384422',
    'YDNTS': '127.02710693'}]}}

In [34]:
import pandas as pd
temp = []
for d in l_data['SeoulPublicLibraryInfo']['row']:
    temp.append(d)

In [40]:
l_unl = pd.DataFrame(temp)
l_unl.head(3)

,LBRRY_SEQ_NO,LBRRY_NAME,GU_CODE,CODE_VALUE,ADRES,TEL_NO,HMPG_URL,OP_TIME,FDRM_CLOSE_DATE,LBRRY_SE_NAME,XCNTS,YDNTS
0,1935,강남구립못골도서관,0008,강남구,서울특별시 강남구 자곡로 116,02-459-5522,http://library.gangnam.go.kr/mglib,"평일 : 09:00~22:00, 주말 : 09:00~22:00",매주 화요일 및 법정공휴일,공공도서관,37.47153836,127.096582
1,1066,강남역삼푸른솔도서관,0008,강남구,서울특별시 강남구 테헤란로8길 36. 4층,02-2051-1178,https://library.gangnam.go.kr/ysplib/index.do,"평일 : 09:00~18:00, 주말 : 09:00~17:00",매주 화요일 및 법정 공휴일,공공도서관,37.4964968,127.0320274
2,2815,개포하늘꿈도서관,0008,강남구,서울특별시 강남구 개포로 110길 54,02-451-1511,https://library.gangnam.go.kr/hnkklib/,"평일 : 09:00~22:00, 주말 : 09:00~17:00",매주 화요일 및 법정공휴일,공공도서관,37.4906692944468,127.080356908422

In [41]:
import folium
anMap = folium.Map(location=[37.4733061524019,127.099727862691],
                   zoom_start=11,
                   zoom_control=False,
                   control_scale=True)
anMap

In [42]:
from folium.plugins import MarkerCluster
mc = MarkerCluster().add_to(anMap)

for n, row in l_unl.iterrows():
  folium.Marker(location = [row['XCNTS'],row['YDNTS']], popup = folium.Popup(row['LBRRY_NAME'],max_width=300)).add_to(mc)
anMap